@startuml
class OptionForm <<partial>> {
    - components : System.ComponentModel.IContainer = null
    # <<override>> Dispose(disposing:bool) : void
    - InitializeComponent() : void
    - panel1 : System.Windows.Forms.Panel
    - editHistorySize : System.Windows.Forms.NumericUpDown
    - label1 : System.Windows.Forms.Label
    - panelMenu : System.Windows.Forms.Panel
    - panel3 : System.Windows.Forms.Panel
    - label2 : System.Windows.Forms.Label
    - listCounters : System.Windows.Forms.ListBox
    - listShowTitle : System.Windows.Forms.ComboBox
    - label3 : System.Windows.Forms.Label
    - label4 : System.Windows.Forms.Label
    - listShowCurrentValue : System.Windows.Forms.ComboBox
    - label5 : System.Windows.Forms.Label
    - listGraphType : System.Windows.Forms.ComboBox
    - label6 : System.Windows.Forms.Label
    - btnMenuGeneral : System.Windows.Forms.Button
    - panel4 : System.Windows.Forms.Panel
    - btnMenuCounters : System.Windows.Forms.Button
    - tabControl1 : System.Windows.Forms.TabControl
    - tabPage1 : System.Windows.Forms.TabPage
    - tabPage2 : System.Windows.Forms.TabPage
    - groupBox1 : System.Windows.Forms.GroupBox
    - label8 : System.Windows.Forms.Label
    - button1 : System.Windows.Forms.Button
    - tabPage3 : System.Windows.Forms.TabPage
    - label9 : System.Windows.Forms.Label
    - lblVersion : System.Windows.Forms.Label
    - label13 : System.Windows.Forms.Label
    - label11 : System.Windows.Forms.Label
    - label10 : System.Windows.Forms.Label
    - linkLabel2 : System.Windows.Forms.LinkLabel
    - linkLabel1 : System.Windows.Forms.LinkLabel
    - label15 : System.Windows.Forms.Label
    - label14 : System.Windows.Forms.Label
    - textBox1 : System.Windows.Forms.TextBox
    - label16 : System.Windows.Forms.Label
    - groupBox2 : System.Windows.Forms.GroupBox
    - groupBox3 : System.Windows.Forms.GroupBox
    - panelFooter : System.Windows.Forms.Panel
    - buttonApply : System.Windows.Forms.Button
    - lblLatestVersion : System.Windows.Forms.Label
    - label18 : System.Windows.Forms.Label
    - btnCheckUpdate : System.Windows.Forms.Button
    - listSummaryPosition : System.Windows.Forms.ComboBox
    - label19 : System.Windows.Forms.Label
    - checkShowSummary : System.Windows.Forms.CheckBox
    - label20 : System.Windows.Forms.Label
    - checkInvertOrder : System.Windows.Forms.CheckBox
    - label21 : System.Windows.Forms.Label
    - label22 : System.Windows.Forms.Label
    - labelTitle : System.Windows.Forms.Label
    - editPollTime : System.Windows.Forms.NumericUpDown
    - listTitlePosition : System.Windows.Forms.ComboBox
    - label7 : System.Windows.Forms.Label
    - groupBox4 : System.Windows.Forms.GroupBox
    - checkValueShadowHover : System.Windows.Forms.CheckBox
    - label23 : System.Windows.Forms.Label
    - checkTitleShadowHover : System.Windows.Forms.CheckBox
    - label12 : System.Windows.Forms.Label
    - label31 : System.Windows.Forms.Label
    - checkSeparateScales : System.Windows.Forms.CheckBox
    - linkLatestVersion : System.Windows.Forms.LinkLabel
    - buttonReplicateSettings : Controls.MenuButton
    - contextMenuStripReplicateSettings : System.Windows.Forms.ContextMenuStrip
    - toolStripMenuItem1 : System.Windows.Forms.ToolStripMenuItem
    - toolStripSeparator1 : System.Windows.Forms.ToolStripSeparator
    - buttonResetDefaults : System.Windows.Forms.Button
    - button3 : System.Windows.Forms.Button
    - checkEnabled : System.Windows.Forms.CheckBox
    - label32 : System.Windows.Forms.Label
    - groupBox5 : System.Windows.Forms.GroupBox
    - btnColor2 : System.Windows.Forms.Button
    - label30 : System.Windows.Forms.Label
    - btnColor1 : System.Windows.Forms.Button
    - label29 : System.Windows.Forms.Label
    - btnColorCurrentValueShadow : System.Windows.Forms.Button
    - label27 : System.Windows.Forms.Label
    - btnColorCurrentValue : System.Windows.Forms.Button
    - label28 : System.Windows.Forms.Label
    - btnColorTitleShadow : System.Windows.Forms.Button
    - label26 : System.Windows.Forms.Label
    - btnColorTitle : System.Windows.Forms.Button
    - label25 : System.Windows.Forms.Label
    - btnColorBar : System.Windows.Forms.Button
    - label24 : System.Windows.Forms.Label
    - label17 : System.Windows.Forms.Label
    - swcPreview : SystemWatcherControl
    - label34 : System.Windows.Forms.Label
    - label33 : System.Windows.Forms.Label
    - linkTitleFont : System.Windows.Forms.LinkLabel
    - linkCurrentValueFont : System.Windows.Forms.LinkLabel
    - listThemeType : System.Windows.Forms.ComboBox
    - label35 : System.Windows.Forms.Label
    - panelCustomTheme : System.Windows.Forms.Panel
}
@enduml
