@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

SHOW_PERSON_OUTLINE()
LAYOUT_LANDSCAPE()
title System Context Diagram for taskbar-monitor (Windows 10)
System_Boundary(taskbarmonitor,"taskbar-monitor", $link="taskbar-monitor-CONTAINER_taskbarmonitor.html") {
Container(taskbarmonitorapp, "taskbar-monitor app", ".net", "Original taskbar-monitor for Windows 10", $link="taskbar-monitor-COMPONENT_taskbarmonitorapp.html")
Container_Boundary(taskbarmonitorinstaller,"taskbar-monitor installer", $link="taskbar-monitor-COMPONENT_taskbarmonitorinstaller.html") {
Component(installer, "installer component", "", "")
}
}
Enterprise_Boundary(rnd19873,"Microsoft") {
System(windows10, "Windows 10", "", $link="taskbar-monitor-CONTAINER_windows10.html")
}
Rel(taskbarmonitor, windows10, "hosts itself as a deskband on taskbar")
Rel(windows10, taskbarmonitorapp, "starts on windows initialization as deskband.")
Rel(installer, windows10, "copy files, registers DLL and installer")

@enduml